import { useConnectionStore } from '../state/store';

const CHAT_FILENAME = 'chat_history.json';

export interface ChatMessage {
    id?: string;
    role: 'system' | 'user' | 'assistant';
    content: string;
    timestamp: number;
}

export interface ChatSession {
    id: string;
    title: string;
    messages: ChatMessage[];
    updatedAt: number;
}

export interface PaperChatData {
    paperId: string;
    fileId: string | null;
    currentSessionId: string | null;
    sessions: ChatSession[];
}

export class ChatStorage {
    
    private get conn() {
        return useConnectionStore().conn;
    }

    private sanitize<T>(data: T): T {
        return JSON.parse(JSON.stringify(data));
    }

    async getPaperChats(paperId: string): Promise<PaperChatData | undefined> {
        try {
            const encodedFname = encodeURIComponent(CHAT_FILENAME);
            const response = await this.conn.fetcher.get(`/misc/${paperId}?fname=${encodedFname}`);
            
            if (!response.ok) return undefined;
            return await response.json();
        } catch (e) {
            // Ignore 404 or other errors, return undefined implies no history found
            return undefined;
        }
    }

    async savePaperChats(paperId: string, data: Partial<PaperChatData>) {
        const existing = await this.getPaperChats(paperId);
        
        // Merge strategy: update fields, preserve others
        let newData: PaperChatData;
        
        if (existing) {
            newData = {
                ...existing,
                ...data,
                paperId
            };
        } else {
            newData = {
                paperId,
                fileId: data.fileId || null,
                currentSessionId: data.currentSessionId || null,
                sessions: data.sessions || []
            };
        }
        
        // Sanitize and serialize
        const plainData = this.sanitize(newData);
        const file = new File(
            [JSON.stringify(plainData)], 
            CHAT_FILENAME, 
            { type: "application/json" }
        );
        
        // the fname is randomly generated by the server, need a rename
        const fname = await this.conn.uploadMiscFiles(paperId, [file]);
        await this.conn.renameMiscFile(paperId, fname[0], CHAT_FILENAME, true);
    }
    
    async saveSession(paperId: string, session: ChatSession) {
        const data = await this.getPaperChats(paperId) || {
            paperId,
            fileId: null,
            currentSessionId: session.id,
            sessions: []
        };
        
        const idx = data.sessions.findIndex(s => s.id === session.id);
        if (idx >= 0) {
            data.sessions[idx] = session;
        } else {
            data.sessions.push(session);
        }
        data.currentSessionId = session.id;
        
        return this.savePaperChats(paperId, data);
    }
    
    async deleteSession(paperId: string, sessionId: string) {
        const data = await this.getPaperChats(paperId);
        if (!data) return;
        
        data.sessions = data.sessions.filter(s => s.id !== sessionId);
        if (data.currentSessionId === sessionId) {
            data.currentSessionId = data.sessions.length > 0 ? data.sessions[0].id : null;
        }
        
        return this.savePaperChats(paperId, data);
    }

    // Compatibility wrapper
    async getSession(paperId: string) {
        const data = await this.getPaperChats(paperId);
        if (data && data.currentSessionId) {
            const sess = data.sessions.find(s => s.id === data.currentSessionId);
            if (sess) {
                return {
                    messages: sess.messages,
                    fileId: data.fileId,
                    updatedAt: sess.updatedAt
                };
            }
        }
        return undefined;
    }
}

export const chatStorage = new ChatStorage();
